import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import api from '../../utils/api';
import { canPerform } from '../../utils/permissions';
import { fmtDate, Badge } from '../../utils/helpers.jsx';

const priorities = ['Low', 'Medium', 'High', 'Critical'];
const statuses = ['Open', 'In Progress', 'Waiting', 'Completed', 'Cancelled'];
const initial = { title:'', description:'', action_required:'', comment:'', responsible_person:'', due_date:'', priority:'Medium', status:'Open' };

export default function FollowUpsModule({ project }) {
  const { user } = useAuth();
  const canEdit = canPerform('schedule.edit', user);
  const [rows, setRows] = useState([]); const [form, setForm] = useState(initial); const [selected, setSelected] = useState(null); const [saving, setSaving] = useState(false);
  const load = async () => { const { data } = await api.get(`/followups?project_id=${project.id}`); setRows(data || []); };
  useEffect(() => { load(); }, [project.id]);
  const saveNew = async (e) => { e.preventDefault(); await api.post('/followups', { ...form, project_id: project.id }); setForm(initial); load(); };
  const saveEdit = async () => { if (!selected) return; setSaving(true); await api.patch(`/followups/${selected.id}`, selected); setSaving(false); setSelected(null); load(); };
  const counts = useMemo(() => ({ total: rows.length, pending: rows.filter((r) => !['Completed', 'Cancelled'].includes(r.status)).length, completed: rows.filter((r) => r.status === 'Completed').length, overdue: rows.filter((r) => r.status !== 'Completed' && r.status !== 'Cancelled' && r.due_date && r.due_date < new Date().toISOString().slice(0, 10)).length }), [rows]);

  return <div className="qms-page space-y-4"><div className="qms-page-header"><div><h1 className="qms-title">Project Execution Follow-Ups</h1><p className="qms-subtitle">Track action items, ownership, and due dates.</p></div></div>
    <div className="qms-kpi-grid">{[['Total', counts.total], ['Pending', counts.pending], ['Completed', counts.completed], ['Overdue', counts.overdue]].map(([k,v]) => <div key={k} className="qms-kpi-card"><div className="text-xs text-slate-500 uppercase">{k}</div><div className="text-2xl font-black">{v}</div></div>)}</div>
    <form className="qms-section qms-responsive-grid gap-2" onSubmit={saveNew}><input className="qms-input" placeholder="Follow-up title" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} required /><input className="qms-input" placeholder="Responsible person" value={form.responsible_person} onChange={(e)=>setForm({...form,responsible_person:e.target.value})} /><input type="date" className="qms-input" value={form.due_date} onChange={(e)=>setForm({...form,due_date:e.target.value})} /><select className="qms-input" value={form.priority} onChange={(e)=>setForm({...form,priority:e.target.value})}>{priorities.map((x)=><option key={x}>{x}</option>)}</select><input className="qms-input md:col-span-2" placeholder="Action required" value={form.action_required} onChange={(e)=>setForm({...form,action_required:e.target.value})} /><input className="qms-input" placeholder="Comment" value={form.comment} onChange={(e)=>setForm({...form,comment:e.target.value})} /><button className="qms-button-primary" disabled={!canEdit}>{canEdit ? 'Add Follow-Up' : 'Read-only access'}</button></form>
    <div className="qms-table-wrap qms-table-scroll"><table className="qms-table"><thead><tr><th>Title</th><th>Action Required</th><th>Latest Comment</th><th>Responsible</th><th>Due Date</th><th>Priority</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((r)=><tr key={r.id} className="border-b"><td>{r.title}</td><td>{r.action_required||'—'}</td><td>{r.comment||'—'}</td><td>{r.responsible_person||'—'}</td><td>{fmtDate(r.due_date)}</td><td><Badge value={r.priority}/></td><td><Badge value={r.status}/></td><td><button type="button" className="qms-button-secondary py-1" onClick={()=>setSelected({...r})}>Open</button></td></tr>)}</tbody></table></div>
    {selected && <div className="modal-overlay"><div className="modal-box max-w-3xl rounded-xl p-4 space-y-2"><div className="flex justify-between"><h3 className="font-semibold">Follow-Up Details</h3><button type="button" className="qms-button-secondary py-1" onClick={()=>setSelected(null)}>Close</button></div><div className="grid md:grid-cols-2 gap-2 text-xs"><input className="qms-input" value={selected.title||''} onChange={(e)=>setSelected((p)=>({...p,title:e.target.value}))} disabled={!canEdit}/><input className="qms-input" value={selected.responsible_person||''} onChange={(e)=>setSelected((p)=>({...p,responsible_person:e.target.value}))} disabled={!canEdit}/><input className="qms-input md:col-span-2" value={selected.action_required||''} onChange={(e)=>setSelected((p)=>({...p,action_required:e.target.value}))} disabled={!canEdit}/><textarea className="qms-input md:col-span-2 h-20" value={selected.comment||''} onChange={(e)=>setSelected((p)=>({...p,comment:e.target.value}))} disabled={!canEdit}/><input type="date" className="qms-input" value={(selected.due_date||'').slice(0,10)} onChange={(e)=>setSelected((p)=>({...p,due_date:e.target.value}))} disabled={!canEdit}/><select className="qms-input" value={selected.priority||'Medium'} onChange={(e)=>setSelected((p)=>({...p,priority:e.target.value}))} disabled={!canEdit}>{priorities.map((x)=><option key={x}>{x}</option>)}</select><select className="qms-input" value={selected.status||'Open'} onChange={(e)=>setSelected((p)=>({...p,status:e.target.value}))} disabled={!canEdit}>{statuses.map((s)=><option key={s}>{s}</option>)}</select></div><div className="flex gap-2 justify-end">{canEdit && selected.status !== 'Completed' && <button type="button" className="qms-button-secondary" onClick={()=>setSelected((p)=>({...p,status:'Completed'}))}>Mark Completed</button>}{canEdit && <button type="button" className="qms-button-primary" disabled={saving} onClick={saveEdit}>{saving ? 'Saving...' : 'Update Follow-Up'}</button>}</div></div></div>}
  </div>;
}
